-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 16:14:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP database IF EXISTS `instruMental` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `instruMental` DEFAULT CHARACTER SET utf8 ;
USE `instruMental` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NULL,
  `isActive` boolean NULL,
  `parent` boolean NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATE NULL,
  `estado` VARCHAR(25) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `detallePedido_iddetallePedido` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fk_Pedidos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `instruMental`.`Usuario` (`idUsuario`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_Pedidos_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `instruMental`.`Producto` (`idProducto`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_Pedidos_detallePedido1`
    FOREIGN KEY (`detallePedido_iddetallePedido`)
    REFERENCES `instruMental`.`detallePedido` (`iddetallePedido`)
    ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Producto` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `imagen` VARCHAR(25) NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `instruMental`.`Proveedor` (`idProveedor`)
   ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`ProductoPertenecia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`ProductoPertenecia` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`ProductoPertenecia` (
  `Categoria_idCategoria` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  CONSTRAINT `fk_Categoria_has_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `instruMental`.`Categoria` (`idCategoria`)
   ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_Categoria_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `instruMental`.`Producto` (`idProducto`)
   ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `entidad` TINYINT NULL,
  `identificador` VARCHAR(45) NULL,
  `tfno` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NULL,
  `CIF` VARCHAR(9) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Role` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `fecha_alta` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NULL,
  `apellido1` VARCHAR(35) NULL,
  `apellido2` VARCHAR(35) NULL,
  `password` VARCHAR(35) NOT NULL,
  `mail` VARCHAR(35) NULL,
  `fechaBaja` DATETIME NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`UsuarioRole` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`UsuarioRole` (
  `Role_idRole` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Role_idRole`, `Usuario_idUsuario`),
  CONSTRAINT `fk_Role_has_Usuario_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `instruMental`.`Role` (`idRole`)
   ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_Role_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `instruMental`.`Usuario` (`idUsuario`)
   ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Valoraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`Valoraciones` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`Valoraciones` (
  `idValoraciones` INT NOT NULL AUTO_INCREMENT,
  `fechaValoracion` DATE NULL,
  `contenido` VARCHAR(255) NULL,
  `puntuacion` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idValoraciones`))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `mydb`.`detallePedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instruMental`.`detallePedido` ;

CREATE TABLE IF NOT EXISTS `instruMental`.`detallePedido` (
  `iddetallePedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `precio` DECIMAL NULL,
  `descuento` DECIMAL NULL,
  PRIMARY KEY (`iddetallePedido`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;








CREATE USER 'instrumental'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON * . * TO 'instrumental'@'localhost';